matrix:
  MOLECULE_DISTRO: 
    - centos7
    - centos8
    - almalinux8
    
steps:
  build:
    image: guisea/ansible-molecule
    pull: true
    environment:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
      EPEL_MIRROR_URL: https://mirrors.guise.net.nz/epel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:  
      - molecule --version
      - ansible --version
      - molecule test --all

