---
- name: Converge
  hosts: all
  tasks:
    - name: "Include repo-almalinux"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        epel_specify_mirror: true
        epel_mirror_url: "{{ lookup('env', 'EPEL_MIRROR_URL')"
