---
- name: Converge
  hosts: all
  tasks:
    - name: "Include repo-almalinux"
      include_role:
        name: "repo-epel"
      vars:
        epel_specify_mirror: true
        epel_mirror_url: https://someproxyormirror.org.nz
