---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/guisea/${MOLECULE_DISTRO:-centos8}:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible