---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-${MOLECULE_DISTRO:-centos7}
    image: docker.io/guisea/${MOLECULE_DISTRO:-centos7}:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
role_name_check: 2