---
name: Molecule Test
on: 
  push:
    tags-ignore:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro: ['centos7', 'centos8', 'almalinux8' ]
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
  
    steps:
      - name: Checout Source
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade molecule['docker'] docker 'ansible==2.9.19' 
      - name: Test with molecule
        run: |
          molecule test --all
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
          EPEL_MIRROR_URL: https://pproxy.guise.net.nz/epel
